title: Bulk Replace tag
description: Add-On that allows you to replace the value of a tag in large sets of documents
instructions: ''
type: object
documents:
  - query
  - selected
properties:
  key:
    title: Key 
    type: string
  value:
    title: Value
    type: string
  add_if_missing:
      title: Add the tag if it does not exist
      type: boolean
      default: False
required:
  - key
  - value 
# Categories are what type of Add-On this is. Used to sort the Add-On in the Add-On menu. 
categories: 
  - bulk
version: 2
